# Generated by Django 3.2.15 on 2022-09-22 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('adhar', models.CharField(blank=True, max_length=255)),
                ('adhar_mobile', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('dob', models.CharField(blank=True, max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('spouse', models.CharField(blank=True, max_length=255)),
                ('qulification', models.CharField(blank=True, max_length=255)),
                ('pob', models.CharField(blank=True, max_length=255)),
                ('pan', models.CharField(blank=True, max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('AIncome', models.CharField(blank=True, max_length=255)),
                ('Employer', models.CharField(blank=True, max_length=255)),
                ('service', models.CharField(blank=True, max_length=255)),
                ('new_hash', models.CharField(default='', max_length=500)),
                ('created', models.DateField(auto_now_add=True)),
                ('app_status', models.CharField(default='Pending', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('hospital', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('ENT', models.FileField(upload_to='doc/')),
                ('ED', models.FileField(upload_to='doc/')),
                ('AT', models.FileField(upload_to='doc/')),
                ('HI', models.FileField(upload_to='doc/')),
                ('new_hash', models.CharField(default='', max_length=500)),
                ('created', models.DateField(auto_now_add=True)),
                ('insurence', models.ManyToManyField(blank=True, to='core.Insure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('roll', models.CharField(default='insure', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
